# Generated by Django 4.1.4 on 2022-12-08 23:22

import FileUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to=FileUpload.models.upload_path)),
            ],
        ),
    ]
